### ISSUE TITLE
Is it possible to pass glob to option.maps?

### ISSUE THREAD

**Issue by dtvn** [pascalduez/postcss-map#136] opened 2019-10-24 08:02 UTC
I have a `config` dir, and I would like to call all files in it. Can we somehow do like this:
```Js
'postcss-map':  {
    basePath: 'css',
    maps: ['*.json']
}
```

**Comment by pascalduez** [comment] 2019-10-24 12:05
Hello,

not possible currently. 

Closing because a dupe of #28.

**Closed as completed by pascalduez** 2019-10-24 12:05 UTC
