### ISSUE TITLE
Doesn't work with postcss-color-functions

### ISSUE THREAD

**Issue by admdh** [pascalduez/postcss-map#14] opened 2015-07-25 12:09 UTC
It would be great if postcss-map worked with postcss-color-functions.
Usage of postcss-color-functions is
```
color: color(#fff lightness(50%));
```
but if i use like so
```
color: color(map(white) lightness(50%));
```
it doesn't work. it troughs an error Unable to parse color from string "map(white)".

**Comment by pascalduez** [comment] 2015-07-25 15:00
What's the order of the plugins in your process, maybe try to include postcss-map before postcss -color-functions ?

**Comment by admdh** [comment] 2015-07-25 15:35
i did so but still doesn't work.
```
var autoprefixer      = require('autoprefixer');
var precss            = require('precss');
var pxtorem           = require('postcss-pxtorem');
var modularscale      = require('postcss-modular-scale');
var colorFunction     = require("postcss-color-function");
var customProperties  = require("postcss-custom-properties");
var minmax            = require('postcss-media-minmax');
var customMedia       = require("postcss-custom-media");
var grid              = require('postcss-grid');
var map               = require('postcss-map');
var calc              = require("postcss-math");
var cssnano           = require('cssnano');
...
postcss: function () {
		var settingsPath = path.resolve(__dirname, 'app', 'assets', 'css', 'settings.yml');
		this.addDependency(settingsPath);
		return [
			precss({
				onImport: function (files) {
					files.forEach(this.addDependency);
				}.bind(this)
			}),
			modularscale,
			grid(gridOptions), 
			map(cssMaps), 
			customMedia, 
			customProperties, 
			calc, 
			minmax, 
			autoprefixer, 
			pxtorem(pxtoremWhiteList), 
			colorFunction,
			cssnano
		];
	},
```

**Comment by pascalduez** [comment] 2015-07-27 21:14
I ran a quick test, and it seem to be working fine.
Maybe try to investigate through all your plugins stack ?

```yaml
# config.yml
foo: '#fff'
```
```js
'use strict';

var postcss = require('postcss');
var map = require('./');
var colorFunction = require('postcss-color-function');

var opts = {
  basePath: 'test/fixture',
  maps: [ 'config.yml' ],
};

var input = '.foo { color: color(map(foo) lightness(50%)); }';
var css = postcss([ map(opts), colorFunction ]).process(input).css;
console.log(css);

```
```css
foo { color: rgb(128, 128, 128); }
```

**Comment by pascalduez** [comment] 2015-08-28 12:13
Closing, could not reproduce.

**Closed by pascalduez** 2015-08-28 12:13 UTC
